[project]
name = "ollama-survey-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.2.0",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "scholarly>=1.7.11",
    "tqdm>=4.67.1",
]
